#!/bin/bash
# ============================================================
# Pulse Node Installer
# Usage: curl -fsSL https://pulse.inteliflowai.com/install.sh | bash -s -- --token YOUR_TOKEN
# ============================================================

set -euo pipefail

# Defaults
CLOUD_URL="https://api.inteliflowai.com"
DATA_DIR="/opt/pulse/data"
TOKEN=""
LOG_FILE="/opt/pulse/logs/install.log"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log() { echo -e "${CYAN}[pulse]${NC} $1" | tee -a "$LOG_FILE" 2>/dev/null || echo -e "${CYAN}[pulse]${NC} $1"; }
ok()  { echo -e "${GREEN}[  OK ]${NC} $1" | tee -a "$LOG_FILE" 2>/dev/null || true; }
err() { echo -e "${RED}[FAIL]${NC} $1" | tee -a "$LOG_FILE" 2>/dev/null || true; exit 1; }
warn(){ echo -e "${YELLOW}[WARN]${NC} $1" | tee -a "$LOG_FILE" 2>/dev/null || true; }

# Parse flags
while [[ $# -gt 0 ]]; do
  case $1 in
    --token) TOKEN="$2"; shift 2 ;;
    --cloud-url) CLOUD_URL="$2"; shift 2 ;;
    --data-dir) DATA_DIR="$2"; shift 2 ;;
    *) echo "Unknown flag: $1"; exit 1 ;;
  esac
done

if [ -z "$TOKEN" ]; then
  read -p "Enter registration token: " TOKEN
fi

if [ -z "$TOKEN" ]; then
  err "Registration token is required. Use --token YOUR_TOKEN"
fi

echo ""
echo -e "${CYAN}╔══════════════════════════════════════╗${NC}"
echo -e "${CYAN}║       Pulse Node Installer           ║${NC}"
echo -e "${CYAN}║       by Inteliflow                  ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════╝${NC}"
echo ""

# ── Prerequisites ──
log "Checking prerequisites..."

# Docker
if ! command -v docker &> /dev/null; then
  err "Docker is not installed. Install Docker first: https://docs.docker.com/engine/install/"
fi
ok "Docker found: $(docker --version)"

# Docker Compose v2
if ! docker compose version &> /dev/null; then
  err "Docker Compose v2 is not available. Update Docker or install the compose plugin."
fi
ok "Docker Compose found: $(docker compose version --short)"

# RAM check (8GB+)
TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo 2>/dev/null | awk '{print $2}' || echo 0)
TOTAL_RAM_GB=$((TOTAL_RAM_KB / 1024 / 1024))
if [ "$TOTAL_RAM_GB" -lt 7 ]; then
  warn "System has ${TOTAL_RAM_GB}GB RAM. Recommended: 8GB+"
else
  ok "RAM: ${TOTAL_RAM_GB}GB"
fi

# Disk check (100GB+)
DISK_AVAIL=$(df -BG "${DATA_DIR%/*}" 2>/dev/null | tail -1 | awk '{print $4}' | tr -d 'G' || echo 0)
if [ "$DISK_AVAIL" -lt 100 ]; then
  warn "Only ${DISK_AVAIL}GB disk available. Recommended: 100GB+"
else
  ok "Disk: ${DISK_AVAIL}GB available"
fi

# ── Create directories ──
log "Creating directory structure..."
mkdir -p "$DATA_DIR"/{media,sync/tmp,postgres,jellyfin/config,jellyfin/cache}
mkdir -p /opt/pulse/{config,updates/rollback,updates/staging,logs}
ok "Directories created at /opt/pulse"

# ── Initialize log ──
touch "$LOG_FILE"

# ── Download docker-compose.yml ──
log "Downloading docker-compose.yml..."
COMPOSE_FILE="/opt/pulse/docker-compose.yml"

if [ -f "$COMPOSE_FILE" ]; then
  warn "docker-compose.yml already exists — backing up to docker-compose.yml.bak"
  cp "$COMPOSE_FILE" "${COMPOSE_FILE}.bak"
fi

# Try downloading from cloud, fall back to bundled version
if curl -fsSL "${CLOUD_URL}/releases/latest/docker-compose.yml" -o "$COMPOSE_FILE" 2>/dev/null; then
  ok "Downloaded docker-compose.yml from cloud"
else
  warn "Could not download from cloud — using bundled docker-compose.yml"
  if [ -f "$(dirname "$0")/docker-compose.yml" ]; then
    cp "$(dirname "$0")/docker-compose.yml" "$COMPOSE_FILE"
  else
    err "No docker-compose.yml available. Check your cloud URL: ${CLOUD_URL}"
  fi
fi

# ── Write .env ──
log "Writing .env configuration..."
ENV_FILE="/opt/pulse/.env"
POSTGRES_PASSWORD=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32)

if [ -f "$ENV_FILE" ]; then
  warn ".env already exists — preserving existing configuration"
else
  cat > "$ENV_FILE" <<EOF
# Pulse Node Configuration — generated by installer
NODE_REGISTRATION_TOKEN=${TOKEN}
CLOUD_API_URL=${CLOUD_URL}

# Local Database
POSTGRES_USER=pulse
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=pulse_node
DATABASE_URL=postgresql://pulse:${POSTGRES_PASSWORD}@postgres:5432/pulse_node

# Jellyfin
JELLYFIN_BASE_URL=http://jellyfin:8096
JELLYFIN_API_KEY=

# Paths
DATA_DIR=${DATA_DIR}
SYNC_DATA_DIR=${DATA_DIR}/sync
MEDIA_DIR=${DATA_DIR}/media
EOF
  ok ".env written"
fi

# ── Start services ──
log "Starting Pulse services..."
cd /opt/pulse
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d 2>&1 | tee -a "$LOG_FILE"
ok "Services started"

# ── Wait for health ──
log "Waiting for node-agent to become healthy..."
HEALTHY=false
for i in $(seq 1 30); do
  if curl -sf http://localhost:3100/health > /dev/null 2>&1; then
    HEALTHY=true
    break
  fi
  sleep 2
done

if [ "$HEALTHY" = false ]; then
  warn "Node-agent not yet healthy — it may still be starting. Check: curl http://localhost:3100/health"
else
  ok "Node-agent is healthy"
fi

# ── Register with cloud ──
log "Registering node with cloud..."
HOSTNAME=$(hostname)
IP_ADDRESS=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "unknown")
DISK_TOTAL=$(df -BG "$DATA_DIR" 2>/dev/null | tail -1 | awk '{print $2}' | tr -d 'G' || echo 0)

REG_RESPONSE=$(curl -sf -X POST "${CLOUD_URL}/api/nodes/register" \
  -H "Content-Type: application/json" \
  -d "{\"registration_token\":\"${TOKEN}\",\"hostname\":\"${HOSTNAME}\",\"version\":\"0.1.0\",\"ip_address\":\"${IP_ADDRESS}\",\"storage_total_gb\":${DISK_TOTAL}}" \
  2>/dev/null) || true

if echo "$REG_RESPONSE" | grep -q "node_id"; then
  NODE_ID=$(echo "$REG_RESPONSE" | grep -o '"node_id":"[^"]*"' | cut -d'"' -f4)
  ok "Registered! Node ID: ${NODE_ID}"

  # Append NODE_ID to .env
  echo "NODE_ID=${NODE_ID}" >> "$ENV_FILE"

  # Restart with NODE_ID
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d 2>&1 | tee -a "$LOG_FILE"
else
  warn "Cloud registration failed (may already be registered, or cloud unreachable). Response: ${REG_RESPONSE}"
fi

# ── Done ──
echo ""
echo -e "${GREEN}╔══════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       Pulse Node Installed!          ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════╝${NC}"
echo ""
echo -e "  Local admin:  ${CYAN}http://localhost:3100${NC}"
echo -e "  Jellyfin:     ${CYAN}http://localhost:8096${NC}"
echo -e "  Config:       ${CYAN}/opt/pulse/.env${NC}"
echo -e "  Data:         ${CYAN}${DATA_DIR}${NC}"
echo -e "  Logs:         ${CYAN}${LOG_FILE}${NC}"
echo ""
echo -e "  Next steps:"
echo -e "  1. Configure Jellyfin API key in /opt/pulse/.env"
echo -e "  2. Run: cd /opt/pulse && docker compose restart"
echo -e "  3. Verify in cloud admin: the node should appear as 'active'"
echo ""
